import { GoogleGenAI } from "@google/genai";
import { MODELS, PROMPTS } from "../constants";

// Helper to convert File to Base64
const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result.split(',')[1]);
      }
    };
    reader.readAsDataURL(file);
  });

  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
};

export const generateTryOnResult = async (
  personFile: File,
  clothFile: File,
  useHighQuality: boolean
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY;
    if (!apiKey) throw new Error("API Key not found");

    const ai = new GoogleGenAI({ apiKey });
    
    // Select model based on user preference
    const modelName = useHighQuality ? MODELS.QUALITY : MODELS.FAST;

    const personPart = await fileToGenerativePart(personFile);
    const clothPart = await fileToGenerativePart(clothFile);

    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [
          personPart,
          clothPart,
          { text: PROMPTS.TRY_ON_USER }
        ]
      },
      config: {
        systemInstruction: PROMPTS.TRY_ON_SYSTEM,
        // We do not set responseMimeType for image generation models typically, 
        // relying on the model to return image parts.
      }
    });

    // Extract the image from the response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};